version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - qr-service
      - ticket-validation-service
      - capacity-service

  auth-service:
    build: ./auth-service
    deploy:
      replicas: 2
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/authdb
    depends_on:
      - mongodb

  qr-service:
    build: ./qr-service
    deploy:
      replicas: 2
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/qrdb

  ticket-validation-service:
    build: ./ticket-validation-service
    deploy:
      replicas: 2
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ticketdb
    depends_on:
      - mongodb

  capacity-service:
    build: ./capacity-service
    deploy:
      replicas: 2
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/capacitydb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge
